-- SQL-dialect for PostgreSQL

-- start Docker PostgreSQL in container: just copy-paste in terminal text below
-- docker run -p 5432:5432 --name postgres -d -it -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=library_db postgres:15

create table person (
    id int primary key generated by default as identity,
    name varchar(100) not null,
    year_of_birth int not null check ( person.year_of_birth > 1950 )
);

create table book (
    book_id int primary key generated by default as identity,
    person_id int references person(id) on delete set null,
    name varchar(100) not null,
    author varchar (100) not null,
    year int not null,
    date_time_bind timestamp
);

insert into person (name, year_of_birth) VALUES ('Andrii Hlybchenko 0.', 1998);
insert into person (name, year_of_birth) VALUES ('Sehii Cherednichenko S.', 1997);
insert into person (name, year_of_birth) VALUES ('Elizaveta Dashko A.', 2000);
insert into person (name, year_of_birth) VALUES ('Bohdan Chernetskii S.', 1992);
insert into person (name, year_of_birth) VALUES ('Aleksandr Karatanov V.', 1986);
insert into person (name, year_of_birth) VALUES ('Dmitro Verhuz V.', 2000);
insert into person (name, year_of_birth) VALUES ('Maryna Galanskya A.', 2000);
insert into person (name, year_of_birth) VALUES ('Evhenyi Stryuk O.', 2008);
insert into person (name, year_of_birth) VALUES ('Stanislav Lindover P.', 1972);
insert into person (name, year_of_birth) VALUES ('Oleksandra Kovalenko O.', 1999);
insert into person (name, year_of_birth) VALUES ('Victoria Artemenko A.', 2001);
insert into person (name, year_of_birth) VALUES ('Volodymyr Zelenskyy O.', 1978);
insert into person (name, year_of_birth) VALUES ('Barack Obama H.', 1961);
insert into person (name, year_of_birth) VALUES ('Elon Musk R.', 1971);

insert into book (person_id, name, author, year, date_time_bind) VALUES (1, 'Kobzar (poetry collection)', 'Taras Shevchenko H.', 1840, '2022-12-24 19:10:25');
insert into book (person_id, name, author, year, date_time_bind) VALUES (null, 'Nineteen Eighty-Four', 'George Orwell', 1949, null);
insert into book (person_id, name, author, year, date_time_bind) VALUES (2, 'Divine Comedy', 'Dante Alighieri', 1720,'2022-12-24 19:10:25');
insert into book (person_id, name, author, year, date_time_bind) VALUES (4, 'Frankenstein; or, The Modern Prometheus ', 'Mary Shelley', 1818, '2022-12-24 19:10:25');
insert into book (person_id, name, author, year, date_time_bind) VALUES (11, 'Kallocain', 'Karin Boye', 1940, '2023-01-20 10:52:52');
insert into book (person_id, name, author, year, date_time_bind) VALUES (1, 'Atlas Shrugged', 'Ayn Rand', 1957, '2023-01-20 10:52:52');
insert into book (person_id, name, author, year, date_time_bind) VALUES (3, 'Fahrenheit 451', 'Ray Bradbury', 1953, '2023-01-20 10:52:52');
insert into book (person_id, name, author, year, date_time_bind) VALUES (5, 'The Great Gatsby', 'Scott Fitzgerald F.', 1925, '2023-01-20 10:52:52');
insert into book (person_id, name, author, year, date_time_bind) VALUES (null, 'Crime and Punishment', 'Fyodor Dostoevsky M,', 1866, null);
insert into book (person_id, name, author, year, date_time_bind) VALUES (6, 'Moby-Dick', 'Herman Melville', 1851,'2023-01-20 10:52:52');
insert into book (person_id, name, author, year, date_time_bind) VALUES (8, 'Dracula', 'Bram Stoker', 1897, '2023-01-20 10:52:52');
insert into book (person_id, name, author, year, date_time_bind) VALUES (null, 'The Lord of the Rings', 'J. R. R. Tolkien', 1954, null);
insert into book (person_id, name, author, year, date_time_bind) VALUES (10, 'The Adventures of Huckleberry Finn', 'Mark Twain ', 1884, '2023-01-20 10:52:52');
insert into book (person_id, name, author, year, date_time_bind) VALUES (3, 'The Iliad', 'Homer', -800, '2023-01-20 10:52:52');
insert into book (person_id, name, author, year, date_time_bind) VALUES (9, 'Animal Farm ', 'George Orwell', 1945, '2023-01-20 10:52:52');
insert into book (person_id, name, author, year, date_time_bind) VALUES (14, 'The Castle', 'Franz Kafka', 1920, '2023-01-20 10:52:52');
insert into book (person_id, name, author, year, date_time_bind) VALUES (null, 'The Art of War', 'Sun Tzu', -5000, null);